### ISSUE TITLE
libR.Normal().rnorm(0) returns a 2-array

### ISSUE THREAD

**Issue by ellis** [R-js/libRmath.js#8]
Looks like `rnorm(0)` is acting like `rnorm(2)`:

```
> const libR = require('lib-r-math.js');
undefined
> libR.Normal().rnorm(0);
[ 1.2629542848807933, -0.3262333607056494 ]
```

Obviously, we wouldn't normally pass `n=0` to `rnorm`, but `n` could be a variable that is calculated elsewhere.

**Comment by jacobbogers** [comment]
Thanks a lot Ellis,
I dont know what happened, seems a merge with the last fix branch didnt happen correctly

I tested
```
const n= libR.Normal()
> n.rnorm()
1.2629542848807933
> n.rnorm(1)
-0.3262333607056494
> n.rnorm(0)
[]
> n.rnorm(2)
[ 1.3297992629225006, 1.2724293214294047 ]
> n.rnorm(-1)
[]
```
The version is now 1.0.82 on npm  
lib-r-math.js@1.0.82

**Comment by jacobbogers** [comment]
In All cases I will return arrays (in progress, but will take a while because it's not a trivial change and everything needs to be tested)  also I am porting blas/lapack to JS (because R `solve`, `lm` and `glm`)

will prolly add an helper like   `empty` which will give (true /false)  

` if (!empty( rnorm( n , 1,2) ) { ....`  looks nicer  then  `if (rnorm(n,1,2).length) {....`

**Comment by ellis** [comment]
Thanks @jacobbogers !

**Comment by jacobbogers** [comment]
Hi,
I am going to revert some things
in R
```
rnorm(-1) gives an error, this is different then in in above example , will throw an exception aswell
rnorm(0) gives an empty array  `numeric(0)`
